"""initial_migration

Revision ID: fe459c9d78eb
Revises: 
Create Date: 2026-01-05 14:48:23.938437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe459c9d78eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_account_id'), 'boards', ['account_id'], unique=False)
    op.create_index(op.f('ix_boards_id'), 'boards', ['id'], unique=False)
    op.create_table('gamification_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('is_system_badge', sa.Boolean(), nullable=False),
    sa.Column('criteria_type', sa.String(length=50), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_badges_account_id'), 'gamification_badges', ['account_id'], unique=False)
    op.create_index(op.f('ix_gamification_badges_id'), 'gamification_badges', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_account_id'), 'audit_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('automations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('automation_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.String(length=50), nullable=True),
    sa.Column('trigger_conditions', sa.JSON(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(length=20), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('auto_disable_on_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automations_account_id'), 'automations', ['account_id'], unique=False)
    op.create_index(op.f('ix_automations_automation_type'), 'automations', ['automation_type'], unique=False)
    op.create_index(op.f('ix_automations_board_id'), 'automations', ['board_id'], unique=False)
    op.create_index(op.f('ix_automations_id'), 'automations', ['id'], unique=False)
    op.create_index(op.f('ix_automations_next_run_at'), 'automations', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_automations_priority'), 'automations', ['priority'], unique=False)
    op.create_index(op.f('ix_automations_trigger_event'), 'automations', ['trigger_event'], unique=False)
    op.create_table('field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_definitions_board_id'), 'field_definitions', ['board_id'], unique=False)
    op.create_index(op.f('ix_field_definitions_id'), 'field_definitions', ['id'], unique=False)
    op.create_table('gamification_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_points_id'), 'gamification_points', ['id'], unique=False)
    op.create_index(op.f('ix_gamification_points_reason'), 'gamification_points', ['reason'], unique=False)
    op.create_index(op.f('ix_gamification_points_user_id'), 'gamification_points', ['user_id'], unique=False)
    op.create_table('gamification_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('cards_won', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_type', 'period_start', name='unique_user_ranking_period')
    )
    op.create_index(op.f('ix_gamification_rankings_id'), 'gamification_rankings', ['id'], unique=False)
    op.create_index(op.f('ix_gamification_rankings_period_end'), 'gamification_rankings', ['period_end'], unique=False)
    op.create_index(op.f('ix_gamification_rankings_period_start'), 'gamification_rankings', ['period_start'], unique=False)
    op.create_index(op.f('ix_gamification_rankings_period_type'), 'gamification_rankings', ['period_type'], unique=False)
    op.create_index(op.f('ix_gamification_rankings_user_id'), 'gamification_rankings', ['user_id'], unique=False)
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_done_stage', sa.Boolean(), nullable=False),
    sa.Column('is_lost_stage', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_board_id'), 'lists', ['board_id'], unique=False)
    op.create_index(op.f('ix_lists_id'), 'lists', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('notification_metadata', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('awarded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['awarded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['badge_id'], ['gamification_badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='unique_user_badge')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_won', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_assigned_to_id'), 'cards', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_list_id'), 'cards', ['list_id'], unique=False)
    op.create_index(op.f('ix_cards_title'), 'cards', ['title'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_card_id'), 'activities', ['card_id'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('automation_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('execution_data', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_executions_automation_id'), 'automation_executions', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_card_id'), 'automation_executions', ['card_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_id'), 'automation_executions', ['id'], unique=False)
    op.create_index(op.f('ix_automation_executions_started_at'), 'automation_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_automation_executions_status'), 'automation_executions', ['status'], unique=False)
    op.create_table('card_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'field_definition_id', name='unique_card_field')
    )
    op.create_index(op.f('ix_card_field_values_card_id'), 'card_field_values', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_field_values_field_definition_id'), 'card_field_values', ['field_definition_id'], unique=False)
    op.create_index(op.f('ix_card_field_values_id'), 'card_field_values', ['id'], unique=False)
    op.create_table('card_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_batch_transfer', sa.Boolean(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_transfers_batch_id'), 'card_transfers', ['batch_id'], unique=False)
    op.create_index(op.f('ix_card_transfers_card_id'), 'card_transfers', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_transfers_from_user_id'), 'card_transfers', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_card_transfers_id'), 'card_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_card_transfers_status'), 'card_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_card_transfers_to_user_id'), 'card_transfers', ['to_user_id'], unique=False)
    op.create_table('transfer_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['card_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_approvals_approver_id'), 'transfer_approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_transfer_approvals_expires_at'), 'transfer_approvals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_transfer_approvals_id'), 'transfer_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_approvals_status'), 'transfer_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_transfer_approvals_transfer_id'), 'transfer_approvals', ['transfer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_approvals_transfer_id'), table_name='transfer_approvals')
    op.drop_index(op.f('ix_transfer_approvals_status'), table_name='transfer_approvals')
    op.drop_index(op.f('ix_transfer_approvals_id'), table_name='transfer_approvals')
    op.drop_index(op.f('ix_transfer_approvals_expires_at'), table_name='transfer_approvals')
    op.drop_index(op.f('ix_transfer_approvals_approver_id'), table_name='transfer_approvals')
    op.drop_table('transfer_approvals')
    op.drop_index(op.f('ix_card_transfers_to_user_id'), table_name='card_transfers')
    op.drop_index(op.f('ix_card_transfers_status'), table_name='card_transfers')
    op.drop_index(op.f('ix_card_transfers_id'), table_name='card_transfers')
    op.drop_index(op.f('ix_card_transfers_from_user_id'), table_name='card_transfers')
    op.drop_index(op.f('ix_card_transfers_card_id'), table_name='card_transfers')
    op.drop_index(op.f('ix_card_transfers_batch_id'), table_name='card_transfers')
    op.drop_table('card_transfers')
    op.drop_index(op.f('ix_card_field_values_id'), table_name='card_field_values')
    op.drop_index(op.f('ix_card_field_values_field_definition_id'), table_name='card_field_values')
    op.drop_index(op.f('ix_card_field_values_card_id'), table_name='card_field_values')
    op.drop_table('card_field_values')
    op.drop_index(op.f('ix_automation_executions_status'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_started_at'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_card_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_automation_id'), table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_card_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_cards_title'), table_name='cards')
    op.drop_index(op.f('ix_cards_list_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_assigned_to_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_lists_id'), table_name='lists')
    op.drop_index(op.f('ix_lists_board_id'), table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_gamification_rankings_user_id'), table_name='gamification_rankings')
    op.drop_index(op.f('ix_gamification_rankings_period_type'), table_name='gamification_rankings')
    op.drop_index(op.f('ix_gamification_rankings_period_start'), table_name='gamification_rankings')
    op.drop_index(op.f('ix_gamification_rankings_period_end'), table_name='gamification_rankings')
    op.drop_index(op.f('ix_gamification_rankings_id'), table_name='gamification_rankings')
    op.drop_table('gamification_rankings')
    op.drop_index(op.f('ix_gamification_points_user_id'), table_name='gamification_points')
    op.drop_index(op.f('ix_gamification_points_reason'), table_name='gamification_points')
    op.drop_index(op.f('ix_gamification_points_id'), table_name='gamification_points')
    op.drop_table('gamification_points')
    op.drop_index(op.f('ix_field_definitions_id'), table_name='field_definitions')
    op.drop_index(op.f('ix_field_definitions_board_id'), table_name='field_definitions')
    op.drop_table('field_definitions')
    op.drop_index(op.f('ix_automations_trigger_event'), table_name='automations')
    op.drop_index(op.f('ix_automations_priority'), table_name='automations')
    op.drop_index(op.f('ix_automations_next_run_at'), table_name='automations')
    op.drop_index(op.f('ix_automations_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_board_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_automation_type'), table_name='automations')
    op.drop_index(op.f('ix_automations_account_id'), table_name='automations')
    op.drop_table('automations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_account_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_gamification_badges_id'), table_name='gamification_badges')
    op.drop_index(op.f('ix_gamification_badges_account_id'), table_name='gamification_badges')
    op.drop_table('gamification_badges')
    op.drop_index(op.f('ix_boards_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_account_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
