"""add_gamification_action_points_table

Revision ID: 6be5ab0d12dc
Revises: d0a5404c934d
Create Date: 2026-02-04 10:23:56.541163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be5ab0d12dc'
down_revision = 'd0a5404c934d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamification_action_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_action_points_action_type'), 'gamification_action_points', ['action_type'], unique=True)
    op.create_index(op.f('ix_gamification_action_points_id'), 'gamification_action_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gamification_action_points_id'), table_name='gamification_action_points')
    op.drop_index(op.f('ix_gamification_action_points_action_type'), table_name='gamification_action_points')
    op.drop_table('gamification_action_points')
    # ### end Alembic commands ###
