"""add_products_and_card_products_tables

Revision ID: cb8c49b2c082
Revises: f11b4bd133d0
Create Date: 2026-01-27 11:18:45.284818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8c49b2c082'
down_revision = 'f11b4bd133d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
