"""add_card_tasks_table

Revision ID: f11b4bd133d0
Revises: a1b2c3d4e5f6
Create Date: 2026-01-27 10:23:49.187749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f11b4bd133d0'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('CALL', 'MEETING', 'TASK', 'DEADLINE', 'EMAIL', 'LUNCH', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('video_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('FREE', 'BUSY', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_tasks_assigned_to_id'), 'card_tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_card_tasks_card_id'), 'card_tasks', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_tasks_due_date'), 'card_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_card_tasks_id'), 'card_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_card_tasks_is_completed'), 'card_tasks', ['is_completed'], unique=False)
    op.create_index(op.f('ix_card_tasks_task_type'), 'card_tasks', ['task_type'], unique=False)
    op.drop_index(op.f('ix_gamification_action_points_action_type'), table_name='gamification_action_points')
    op.drop_index(op.f('ix_gamification_action_points_id'), table_name='gamification_action_points')
    op.drop_table('gamification_action_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamification_action_points',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('gamification_action_points_pkey'))
    )
    op.create_index(op.f('ix_gamification_action_points_id'), 'gamification_action_points', ['id'], unique=False)
    op.create_index(op.f('ix_gamification_action_points_action_type'), 'gamification_action_points', ['action_type'], unique=True)
    op.drop_index(op.f('ix_card_tasks_task_type'), table_name='card_tasks')
    op.drop_index(op.f('ix_card_tasks_is_completed'), table_name='card_tasks')
    op.drop_index(op.f('ix_card_tasks_id'), table_name='card_tasks')
    op.drop_index(op.f('ix_card_tasks_due_date'), table_name='card_tasks')
    op.drop_index(op.f('ix_card_tasks_card_id'), table_name='card_tasks')
    op.drop_index(op.f('ix_card_tasks_assigned_to_id'), table_name='card_tasks')
    op.drop_table('card_tasks')
    # ### end Alembic commands ###
