"""add_call_logs_table

Revision ID: d0a5404c934d
Revises: 2026_02_02_1322
Create Date: 2026-02-02 15:43:01.861119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0a5404c934d'
down_revision = '2026_02_02_1322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID do vendedor que fez a chamada'),
    sa.Column('card_id', sa.Integer(), nullable=False, comment='ID do card de onde a chamada foi originada'),
    sa.Column('phone', sa.String(length=50), nullable=False, comment='Telefone chamado'),
    sa.Column('extension', sa.String(length=50), nullable=False, comment='Ramal usado para fazer a chamada'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status da chamada: pending, ringing, completed, failed, no_answer'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Duração da chamada em segundos'),
    sa.Column('recording_url', sa.Text(), nullable=True, comment='URL da gravação da chamada'),
    sa.Column('api4com_call_id', sa.String(length=255), nullable=True, comment='ID da chamada na API4COM'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Mensagem de erro, se houver'),
    sa.Column('call_metadata', sa.Text(), nullable=True, comment='Metadata adicional da chamada (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Quando a chamada foi iniciada'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última atualização'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_api4com_call_id'), 'call_logs', ['api4com_call_id'], unique=True)
    op.create_index(op.f('ix_call_logs_card_id'), 'call_logs', ['card_id'], unique=False)
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_call_logs_user_id'), 'call_logs', ['user_id'], unique=False)
    op.drop_index('ix_gamification_action_points_action_type', table_name='gamification_action_points')
    op.drop_index('ix_gamification_action_points_id', table_name='gamification_action_points')
    op.drop_table('gamification_action_points')
    op.drop_index('ix_cards_contact_info_backup_card_id', table_name='cards_contact_info_backup')
    op.drop_table('cards_contact_info_backup')
    op.drop_index('ix_api4com_config_is_active', table_name='api4com_config')
    op.alter_column('leads', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_extensions', 'extension',
               existing_type=sa.VARCHAR(length=50),
               comment="Ramal do vendedor na API4COM (ex: '1000')",
               existing_comment='Ramal do vendedor na API4COM',
               existing_nullable=False)
    op.drop_index('ix_user_extensions_is_active', table_name='user_extensions')
    op.drop_constraint('uq_user_extensions_extension', 'user_extensions', type_='unique')
    op.drop_constraint('uq_user_extensions_user_id', 'user_extensions', type_='unique')
    op.drop_index('ix_user_extensions_extension', table_name='user_extensions')
    op.create_index(op.f('ix_user_extensions_extension'), 'user_extensions', ['extension'], unique=True)
    op.drop_index('ix_user_extensions_user_id', table_name='user_extensions')
    op.create_index(op.f('ix_user_extensions_user_id'), 'user_extensions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_extensions_user_id'), table_name='user_extensions')
    op.create_index('ix_user_extensions_user_id', 'user_extensions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_extensions_extension'), table_name='user_extensions')
    op.create_index('ix_user_extensions_extension', 'user_extensions', ['extension'], unique=False)
    op.create_unique_constraint('uq_user_extensions_user_id', 'user_extensions', ['user_id'])
    op.create_unique_constraint('uq_user_extensions_extension', 'user_extensions', ['extension'])
    op.create_index('ix_user_extensions_is_active', 'user_extensions', ['is_active'], unique=False)
    op.alter_column('user_extensions', 'extension',
               existing_type=sa.VARCHAR(length=50),
               comment='Ramal do vendedor na API4COM',
               existing_comment="Ramal do vendedor na API4COM (ex: '1000')",
               existing_nullable=False)
    op.alter_column('leads', 'custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_api4com_config_is_active', 'api4com_config', ['is_active'], unique=False)
    op.create_table('cards_contact_info_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('backed_up_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cards_contact_info_backup_pkey')
    )
    op.create_index('ix_cards_contact_info_backup_card_id', 'cards_contact_info_backup', ['card_id'], unique=False)
    op.create_table('gamification_action_points',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gamification_action_points_pkey')
    )
    op.create_index('ix_gamification_action_points_id', 'gamification_action_points', ['id'], unique=False)
    op.create_index('ix_gamification_action_points_action_type', 'gamification_action_points', ['action_type'], unique=True)
    op.drop_index(op.f('ix_call_logs_user_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_card_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_api4com_call_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
